version: '3.8'

services:
  web:
    build: .
    container_name: personal-website
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "description=Personal website running on Nginx"
      - "maintainer=john.doe@example.com"